### ISSUE TITLE
Ecowitt plugin fails to load after upgrade to 2023.4.4

### ISSUE THREAD

**Issue by crempp** [garbled1/homeassistant_ecowitt#147]
I upgraded to 2023.4.4 and now the Ecowitt plugin will not load. I'm receiving this error message in the logs.

```
Setup failed for custom integration ecowitt: Unable to import component: cannot import name 'EcoWittListener' from 'pyecowitt' (/usr/local/lib/python3.10/site-packages/pyecowitt/__init__.py)
```

**Comment by crempp** [comment]
I just updated to 2023.4.5 and the problem solved itself.
