### ISSUE TITLE
Ecowitt doesn't work after HA upgrade!

### ISSUE THREAD

**Issue by Jonvelle53** [garbled1/homeassistant_ecowitt#155]

**Comment by Jonvelle53** [comment]
Do you also get support here, or where?
Sorry, but my English is very bad.

**Comment by cdohrman** [comment]
same here, not sure how to handle it and not sure where to get support and who would fix it.

**Comment by albenex** [comment]
had same issue because updated to HA 2023.5 while using HACS Ecowitt integration.
solved by:
-removing HACS Ecowitt integration (bypass warning that integration is configured)
-reboot HA
-remove old zombie Ecowitt configuration
-reboot HA
-add new configuration for Ecowitt using already-included Ecowitt integration

note: obviously IP will remain the same but endpoint path and port for server will change, depending on your configuration.
note2: you'll have to rename old entities on frontend because names will be different.

**Comment by FeroX-Ron** [comment]
-reboot HA
all steps done

 -remove old zombie Ecowitt configuration -reboot 
where to remove?

**Comment by albenex** [comment]
> -reboot HA all steps done
> 
> -remove old zombie Ecowitt configuration -reboot where to remove?

in my case i still had old entities configured so i went to Settings - Integrations, selected and removed Ecowitt integration using 3 dots -> remove and then restarted.
maybe you already deleted old integration.

**Comment by FeroX-Ron** [comment]
thanks, was my bad

**Comment by Jonvelle53** [comment]
Thx - felt after 50 deletion attempts and subsequent restart of the HA software, then everything old had actually disappeared. Now the new installation of the Ecowitt integration works.
________________________________
Von: albenex ***@***.***>
Gesendet: Monday, May 8, 2023 12:42:21 PM
An: garbled1/homeassistant_ecowitt ***@***.***>
Cc: Jonvelle53 ***@***.***>; Author ***@***.***>
Betreff: Re: [garbled1/homeassistant_ecowitt] Ecowitt doesn't work after HA upgrade! (Issue #155)


-reboot HA all steps done

-remove old zombie Ecowitt configuration -reboot where to remove?

in my case i still had old entities configured so i went to Settings - Integrations, selected and removed Ecowitt integration using 3 dots -> remove and then restarted.
maybe you already deleted old integration.

**Comment by seidler2547** [comment]
Deleting the integration doesn't work:

```
2023-05-09 16:36:45.352 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/homeassistant/homeassistant/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/homeassistant/homeassistant/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/homeassistant/homeassistant/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/homeassistant/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/home/homeassistant/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/home/homeassistant/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/home/homeassistant/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/home/homeassistant/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/home/homeassistant/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/home/homeassistant/homeassistant/lib/python3.10/site-packages/homeassistant/components/config/config_entries.py", line 86, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/home/homeassistant/homeassistant/lib/python3.10/site-packages/homeassistant/config_entries.py", line 1072, in async_remove
    await entry.async_remove(self.hass)
  File "/home/homeassistant/homeassistant/lib/python3.10/site-packages/homeassistant/config_entries.py", line 578, in async_remove
    component = integration.get_component()
  File "/home/homeassistant/homeassistant/lib/python3.10/site-packages/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/ecowitt/__init__.py", line 20, in <module>
    from homeassistant.helpers.entity_registry import (
ImportError: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/home/homeassistant/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_registry.py)
```

**Comment by seidler2547** [comment]
Sorry, but the information given here is wrong. In the current state, this integration cannot work with Home Assistant 2023.5 because of an incompatibility. Here is the fix: https://github.com/garbled1/homeassistant_ecowitt/pull/153

**Comment by Jonvelle53** [comment]
Ok., thx

**Comment by kpWl** [comment]
Das Gleiche Problem habe ich seit HA 2023.5. Ich bin ohne Unterstützung nicht in der Lage, meine ecowitt wieder online zu bekommen - SCHADE. Kann ich irgendwie zu    der Vorversion zurück?

**Comment by Jonvelle53** [comment]
Also nachdem ich gefühlt 50x gelöscht habe. In HACS und bei den Integrationen, und danach jedesmal HA neu gestartet habe, war es dann msl weg.
________________________________
Von: kpWl ***@***.***>
Gesendet: Thursday, May 11, 2023 10:14:46 PM
An: garbled1/homeassistant_ecowitt ***@***.***>
Cc: Jonvelle53 ***@***.***>; Author ***@***.***>
Betreff: Re: [garbled1/homeassistant_ecowitt] Ecowitt doesn't work after HA upgrade! (Issue #155)


Das Gleiche Problem habe ich seit HA 2023.5. Ich bin ohne Unterstützung nicht in der Lage, meine ecowitt wieder online zu bekommen - SCHADE. Kann ich irgendwie zu der Vorversion zurück?

**Comment by FeroX-Ron** [comment]
Hallo @Jonvelle53 ,

die alte Integration in HACS löschen.
Neustart
Danach die Integration aus dem Core (ecowitt) installieren, also nix mehr über HACS

Das ist jetzt eine offizielle Integration.

LG Ron

**Comment by Jonvelle53** [comment]
Danke Dir. Das hatte ich schon verstanden. Allerdings ging das Löschen irgendwie nicht. Gefühlt erst nach dem 50-sten mal nebst Neustarts.
Jetzt hab ich's endlich geschafft!
LG Luz

**Comment by Jonvelle53** [comment]
ja, danke. Habe ich so hinbekommen.
________________________________
Von: FeroX-Ron ***@***.***>
Gesendet: Friday, May 12, 2023 7:41:56 AM
An: garbled1/homeassistant_ecowitt ***@***.***>
Cc: Jonvelle53 ***@***.***>; Mention ***@***.***>
Betreff: Re: [garbled1/homeassistant_ecowitt] Ecowitt doesn't work after HA upgrade! (Issue #155)


Hallo @Jonvelle53<https://github.com/Jonvelle53> ,

die alte Integration in HACS löschen.
Neustart
Danach die Integration aus dem Core (ecowitt) installieren, also nix mehr über HACS

Das ist jetzt eine offizielle Integration.

LG Ron

**Comment by snarlingllama** [comment]
Quick question, for the posts on this issue that are describing the installation of the "new" Ecowitt integration...

Are you reinstalling the HACS instance or the official integration?

**Comment by albenex** [comment]
> Quick question, for the posts on this issue that are describing the installation of the "new" Ecowitt integration...
> 
> Are you reinstalling the HACS instance or the official integration?

using official integration  as the old one from HACS is not supported yet

**Comment by Jonvelle53** [comment]
my old installation was the HACS integration! 
And now i have the HA integration.

**Comment by toddeschroder** [comment]
Broken with 2023.5 
### Can't delete.
Tried to delete integration 30+ times and from various controllers followed by restart each time. Enabled or disabled.
No luck.
 
### Can't install.
ERROR: Config flow could not be loaded: {"message":"Invalid handler specified"}
Removed line "registry = await async_get_entity_registry(self.hass)" as stated in #153
No luck.

**Comment by nliaudat** [comment]
cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)

**Comment by ferdfer** [comment]
Solved!!!

Change in /config/custom_components/ecowitt/__init__.py 

This two lines:

https://github.com/garbled1/homeassistant_ecowitt/pull/153/files

**Comment by iNaiks** [comment]
> Solved!!!
> 
> Change in /config/custom_components/ecowitt/**init**.py
> 
> This two lines:
> 
> https://github.com/garbled1/homeassistant_ecowitt/pull/153/files

It works !!!! fantastic !!! 🤩🥳.

**Comment by travisterrell** [comment]
Can confirm that this works, and that it is still required now. Any idea why the PR isn't being approved?

**Comment by Eric-IOT** [comment]
> > Solved!!!
> > Change in /config/custom_components/ecowitt/**init**.py
> > This two lines:
> > https://github.com/garbled1/homeassistant_ecowitt/pull/153/files
> 
> It works !!!! fantastic !!! 🤩🥳.



> Solved!!!
> 
> Change in /config/custom_components/ecowitt/**init**.py
> 
> This two lines:
> 
> https://github.com/garbled1/homeassistant_ecowitt/pull/153/files

just perfect, it solved my case too... i was running the latest version of Hass on Synology... 👍 🥇

**Comment by githubStrini** [comment]
Thanks
