### ISSUE TITLE
Home Assistant Core 2023.5 breaks integration

### ISSUE THREAD

**Issue by pascaltippelt** [garbled1/homeassistant_ecowitt#157]
When upgrading from 2023.4.X to 2023.5.X, the integration does no longer load. Error message:

>  Logger: homeassistant.setup
Source: setup.py:214
First occurred: 11:26:57 (1 occurrences)
Last logged: 11:26:57
Setup failed for custom integration ecowitt: Unable to import component: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)

It is impossible to delete the integration (in my case nothing happens an the integration just stays "active"). So the repository can't be removed.

Possebly relatet log-entrys:

> 2023-05-07 11:30:29.774 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 86, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1072, in async_remove
    await entry.async_remove(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 578, in async_remove
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/ecowitt/__init__.py", line 20, in <module>
    from homeassistant.helpers.entity_registry import (
ImportError: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)

![grafik](https://user-images.githubusercontent.com/2066297/236669803-09c8fdff-1027-43c2-8e9b-fb6de28ddb52.png)

My device:

WS2900_V2.01.18
von ecowitt
Firmware: EasyWeatherV1.6.4

**Comment by JohnMcLear** [comment]
see https://github.com/garbled1/homeassistant_ecowitt/issues/155

duplicate plz close

**Comment by Jonvelle53** [comment]
I have the same! Any idea - how can I delete the integration?

**Comment by pascaltippelt** [comment]
> see https://github.com/garbled1/homeassistant_ecowitt/issues/155
> 
> duplicate plz close

Not entirely. I additionally informed, that I am unable to remove the integration.

**Comment by CamFlyerCH** [comment]
Same here. I renamed and labeled many sensors. So I have to do that all again !?! I would very much like a fix for anyone using this integration !

**Comment by ronjtaylor** [comment]
same here.
Logger: homeassistant
Source: components/sensor/__init__.py:583
First occurred: May 7, 2023 at 5:38:18 AM (14248 occurrences)
Last logged: 6:21:48 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'unknown'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.pm2_5_2_battery has device class battery, state class measurement unit % and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>)

**Comment by ronjtaylor** [comment]
Logger: homeassistant
Source: components/sensor/__init__.py:583
First occurred: May 7, 2023 at 5:38:18 AM (14248 occurrences)
Last logged: 6:21:48 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'unknown'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.pm2_5_2_battery has device class battery, state class measurement unit % and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>)

**Comment by CountOlaf87** [comment]
Same here, I removed it and when I try to add the integration again, I get: Config flow could not be loaded: {"message":"Invalid handler specified"}

Error log:
ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration ecowitt: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)

**Comment by romainlouvet** [comment]
Same and I am not able to remove this integration 😔

**Comment by rpajik** [comment]
> Same and I am not able to remove this integration 😔
Downgrade HA on version 2023.4, it will start working and you will be able to remove it.

**Comment by RXM307** [comment]
you can try my fork it is still working in 2023.5 
https://github.com/RXM307/homeassistant_ecowitt
however I believe Ecowitt is now part of homeassistant core https://github.com/home-assistant/core/tree/dev/homeassistant/components/ecowitt

I haven't tried it myself but have been meaning too

**Comment by pilehave** [comment]
> you can try my fork it is still working in 2023.5 https://github.com/RXM307/homeassistant_ecowitt however I believe Ecowitt is now part of homeassistant core https://github.com/home-assistant/core/tree/dev/homeassistant/components/ecowitt
> 
> I haven't tried it myself but have been meaning too

I can't get the official integration to work. Never had problems with the HACS one and the whole webhook thing has me puzzled as to why it is needed.

**Comment by JohnMcLear** [comment]
I gave up with the official integration and reverted back to HACS as the **official integration doesn't support Official Home Assistant Hardware / OS.**

**Comment by pilehave** [comment]
Same thing here. The official integration requires all kinds of reverse proxy if you use https and offers nothing that is not in the HACS version.

**Comment by rbauman70** [comment]
Yeah, I guess getting the integration into the core adds more requirements, like maybe not using private listening ports.  Anyway, I put in a [feature request](https://community.home-assistant.io/t/add-webhook-support-on-non-ssl-port-for-integrations/579725) that would solve the problem.  And I have a [workaround](https://github.com/garbled1/homeassistant_ecowitt/issues/154) for using the new core integration.  Probably a way to do it with Python also.

**Comment by RXM307** [comment]
From what I read the core version also used private listening ports.

**Comment by rbauman70** [comment]
Since we seem to have lost the author's support, maybe we can revert the core's implementation back to the private port method then?  Can you merge your fork?

**Comment by iNaiks** [comment]
This Worked for me, only need to change 2 lines in the .py of ecowitt and works.
Link --> https://github.com/garbled1/homeassistant_ecowitt/issues/155#issuecomment-1609959845

**Comment by iNaiks** [comment]
https://github.com/garbled1/homeassistant_ecowitt/issues/155#issuecomment-1609959845
