### ISSUE TITLE
hassio version 115 issue

### ISSUE THREAD

**Issue by scooper1** [garbled1/homeassistant_ecowitt#23]
the integration will not load due to missing constant   UNIT_PERCENTAGE

They have removed the UNIT_ from the constant

to fix edit all instances of UNIT_PERCENTAGE to PERCENTAGE in the __init__.py file

**Comment by MimbaMonkeyHouse** [comment]
When replacing all instances from UNIT_PERCENTAGE to PERCENTAGE, I get this error in the logs:
```
Setup failed for ecowitt: Unable to import component: cannot import name 'PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
23:20:11 – setup.py (ERROR)
```

**Comment by MimbaMonkeyHouse** [comment]
My mistake, this error appeared before I updated to the 115 beta. It disappears when upgraded from 114. I'm still left with these errors and no created entities:
```
2020-09-13 23:32:38 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/pyecowitt/ecowitt.py", line 262, in handler
    weather_data = self.convert_units(data_copy)
  File "/usr/local/lib/python3.8/site-packages/pyecowitt/ecowitt.py", line 163, in convert_units
    data["windspdkmh_avg10m"] = float(data["windspdmph_avg10m"]
TypeError: float expected at most 1 argument, got 2
2020-09-13 23:33:16 WARNING (MainThread) [custom_components.ecowitt] Unhandled sensor type maxdailygustms
``

**Comment by arjen-w** [comment]
I can confirm that the issue is solved with changing UNIT_PERCENTAGE to PERCENTAGE in version 0.115.

**Comment by cpuks** [comment]
Confirm - replacing UNIT_PERCENTAGE to PERCENTAGE solved error. It's related to 0.115 as I made change on 0.114.4 prior to update and addon couldn't start.

**Comment by ronjtaylor** [comment]
I just updated to 115.1 and get this notification 
![image](https://user-images.githubusercontent.com/46874942/93645275-0020e800-fa47-11ea-81f8-56b28eaa1054.png)
and this is display
![image](https://user-images.githubusercontent.com/46874942/93645343-23e42e00-fa47-11ea-8f6a-870e28795445.png)
Been working fine up until 115.1

**Comment by GSzabados** [comment]
I've created a Pull request to get this solved.

**Comment by gilperme** [comment]
The suggestion above worked for my install as well. Thank you.

**Comment by arjen-w** [comment]
> I've created a Pull request to get this solved.

Seems like the pull request was not succesfull:

  File "/hacs/custom_components/hacs/repositories/integration.py", line 32, in localpath
    return f"{self.hacs.core.config_path}/custom_components/{self.data.domain}"
AttributeError: type object 'HacsCore' has no attribute 'config_path'

**Comment by GSzabados** [comment]
@arjen-w, to be honest, I have no idea how to pass the HACS validator.

The changed lines of code is working fine with HASS.IO v0.115 without any issue. If you have experience with HACS validator, then please pass your advise here, and I will look at it. Meanwhile the owner of the integration/repo has not replied to any messages, neither here, neither on the Home Assistant community forum.

**Comment by mr-sneezy** [comment]
If we can't get a PR into this repo can we just create a new fork (until the repo owner want's to get back in to it) and move over to that  ?
What is the etiquette in doing that on Git ?

**Comment by arjen-w** [comment]
> If we can't get a PR into this repo can we just create a new fork (until the repo owner want's to get back in to it) and move over to that ?
> What is the etiquette in doing that on Git ?

Not sure, but as long as you are referring to this project as source in your release notes and code, I personally think it won't be an issue.

On the other hand, for me everything is working after fixing things manually, so for me having a fork isn't necessary at the moment.

**Comment by garbled1** [comment]
Sorry about this.. this is now fixed in 0.3.1  Was very busy for a few months with annoying life stuff.
